spring:
  application:
    name: schedule-planner-authentication
  flyway:
    enabled: true

database:
  url: horvathdavidmiklos.hu
  port: 3306
  schema: schedule_planner
  username: root
  password: Schedule_planner2024

